---
title: "Effects of severe weather events in US on health and economy"
output: html_document
---

<!---
    Language: Your document should be written in English.
    Title: Your document should have a title that briefly summarizes your data analysis
    Synopsis: Immediately after the title, there should be a synopsis which describes and summarizes your analysis in at most 10 complete sentences.
    There should be a section titled Data Processing which describes (in words and code) how the data were loaded into R and processed for analysis. In particular, your analysis must start from the raw CSV file containing the data. You cannot do any preprocessing outside the document. If preprocessing is time-consuming you may consider using the cache = TRUE option for certain code chunks.
    There should be a section titled Results in which your results are presented.
    You may have other sections in your analysis, but Data Processing and Results are required.
    The analysis document must have at least one figure containing a plot.
    Your analyis must have no more than three figures. Figures may have multiple plots in them (i.e. panel plots), but there cannot be more than three figures total.
    You must show all your code for the work in your analysis document. This may make the document a bit verbose, but that is okay. In general, you should ensure that echo = TRUE for every code chunk (this is the default setting in knitr).
 accepted
-->

##Synopsis
In this analysis I explore the effects of severe weather events in the US on health and economy.

##Data Processing

```{r cache = TRUE}
#Download and unzip the data file
#https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2
address <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
address <- sub("^https", "http", address) #https does not work
zipname <- "StormData.csv.bz2"
download.file(address,zipname)

#No need to unzip, R can is smart enough to read a zipped csv
stormdata <- read.csv(zipname)

#housekeeping - remove the zip as it is no longer needed
file.remove(zipname)
#housekeeping
rm(address, zipname)
```

##Explore the data

```{r}

#aggregate over health effects i.e. injuries
#fatalities do no have an effect on population health
#use !is.na or na.rm to exclude NA's
health_injuries_count <- aggregate(INJURIES ~ EVTYPE, data=stormdata, function(x) length( !is.na(x)))
health_injuries_sum <- aggregate(INJURIES ~ EVTYPE, data=stormdata, function(x) sum(x, na.rm = TRUE))
health_injuries_mean <- aggregate(INJURIES ~ EVTYPE, data=stormdata, function(x) mean(x, na.rm = TRUE))

names(health_injuries_count)[2] <- "number"
names(health_injuries_sum)[2] <- "injuries"
names(health_injuries_mean)[2] <- "mean_injuries"

#combine in one dataframe
health <- data.frame(health_injuries_count,
                     health_injuries_sum[2],
                     health_injuries_mean[2]
                     )

#house keeping
rm(health_injuries_count, health_injuries_sum, health_injuries_mean)

health
```


##Results
<!---
    Across the United States, which types of events (as indicated in the EVTYPE variable) are most harmful with respect to population health?
    Across the United States, which types of events have the greatest economic consequences?
-->
